# Generated by Django 6.0.5 on 2026-05-11 17:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after contest')),
            ],
            options={
                'db_table': 'questions_mcq',
            },
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('mcq_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.mcqquestion')),
            ],
            options={
                'db_table': 'questions_mcq_option',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('question_type', models.CharField(choices=[('coding', 'Coding'), ('mcq_single', 'MCQ (Single Answer)'), ('mcq_multiple', 'MCQ (Multiple Answers)'), ('subjective', 'Subjective')], db_index=True, max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in contest')),
                ('marks', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('partial_scoring', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='contests.contest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'questions_question',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_detail', to='questions.question'),
        ),
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField()),
                ('constraints', models.TextField(blank=True)),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('sample_input', models.TextField(blank=True)),
                ('sample_output', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('time_limit_seconds', models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(30)])),
                ('memory_limit_mb', models.PositiveIntegerField(default=256, validators=[django.core.validators.MaxValueValidator(1024)])),
                ('allowed_languages', models.JSONField(default=list, help_text='List of allowed language codes: python, cpp, java, javascript')),
                ('starter_code', models.JSONField(blank=True, default=dict, help_text='Language-keyed starter code: {"python": "...", "cpp": "..."}')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_detail', to='questions.question')),
            ],
            options={
                'db_table': 'questions_coding',
            },
        ),
        migrations.CreateModel(
            name='SubjectiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('guidelines', models.TextField(blank=True, help_text='Grading guidelines for reviewers')),
                ('max_word_count', models.PositiveIntegerField(default=1000)),
                ('reference_answer', models.TextField(blank=True, help_text='Reference answer for grading')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subjective_detail', to='questions.question')),
            ],
            options={
                'db_table': 'questions_subjective',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=True, help_text='Hidden test cases are not shown to candidates')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight for partial scoring', max_digits=5)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('coding_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='questions.codingquestion')),
            ],
            options={
                'db_table': 'questions_testcase',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['contest', 'question_type'], name='questions_q_contest_8d621d_idx'),
        ),
    ]
