# Generated by Django 6.0.5 on 2026-05-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='driver_code',
            field=models.JSONField(blank=True, default=dict, help_text='Language-keyed hidden driver code'),
        ),
    ]
