# Generated by Django 6.0.5 on 2026-05-11 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_focus', 'Page Got Focus'), ('page_blur', 'Page Lost Focus'), ('question_switch', 'Switched Question'), ('code_run', 'Ran Code'), ('code_submit', 'Submitted Code'), ('answer_save', 'Saved Answer'), ('copy', 'Copy Attempted'), ('paste', 'Paste Attempted'), ('keydown', 'Key Pressed'), ('mouse_leave', 'Mouse Left Window')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='contests.contestsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proctoring_activity_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WebcamSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='snapshots/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webcam_snapshots', to='contests.contestsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proctoring_webcam_snapshot',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('window_blur', 'Window Focus Loss'), ('copy_paste', 'Copy/Paste Attempt'), ('right_click', 'Right Click'), ('fullscreen_exit', 'Fullscreen Exit'), ('shortcut_key', 'Keyboard Shortcut'), ('multi_monitor', 'Multiple Monitor Detected'), ('browser_resize', 'Browser Resize'), ('dev_tools', 'Developer Tools Opened'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='violations/screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='contests.contest')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='contests.contestsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proctoring_violation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'violation_type'], name='proctoring__session_0fc503_idx'), models.Index(fields=['contest', 'user'], name='proctoring__contest_874291_idx')],
            },
        ),
    ]
