# Generated by Django 6.0.5 on 2026-05-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.PositiveIntegerField(db_index=True)),
                ('language', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timed Out')], default='queued', max_length=20)),
                ('container_id', models.CharField(blank=True, max_length=100)),
                ('image_used', models.CharField(blank=True, max_length=100)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('execution_time_ms', models.FloatField(blank=True, null=True)),
                ('memory_used_kb', models.FloatField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'execution_job',
                'ordering': ['-queued_at'],
            },
        ),
    ]
