# Generated by Django 6.0.5 on 2026-05-11 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('source_code', models.TextField()),
                ('custom_input', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions_code_draft',
                'unique_together': {('user', 'contest', 'question', 'language')},
            },
        ),
        migrations.CreateModel(
            name='MCQAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.JSONField(default=list)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions_mcq_answer',
                'unique_together': {('user', 'contest', 'question')},
            },
        ),
        migrations.CreateModel(
            name='SubjectiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjective_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions_subjective_answer',
                'unique_together': {('user', 'contest', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=20)),
                ('source_code', models.TextField(blank=True)),
                ('selected_options', models.JSONField(blank=True, default=list)),
                ('answer_text', models.TextField(blank=True)),
                ('verdict', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('runtime_error', 'Runtime Error'), ('time_limit', 'Time Limit Exceeded'), ('memory_limit', 'Memory Limit Exceeded'), ('compilation_error', 'Compilation Error'), ('partial', 'Partial Score'), ('error', 'System Error')], default='pending', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('execution_time_ms', models.FloatField(blank=True, null=True)),
                ('memory_used_kb', models.FloatField(blank=True, null=True)),
                ('compiler_output', models.TextField(blank=True)),
                ('runtime_output', models.TextField(blank=True)),
                ('test_case_results', models.JSONField(blank=True, default=list)),
                ('passed_test_cases', models.PositiveIntegerField(default=0)),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('is_final', models.BooleanField(default=False, help_text='Is this the final submission for scoring')),
                ('submission_number', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.contest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='questions.question')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.contestsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions_submission',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', 'contest', 'question'], name='submissions_user_id_e0c0a8_idx'), models.Index(fields=['verdict'], name='submissions_verdict_223995_idx'), models.Index(fields=['contest', 'user', 'is_final'], name='submissions_contest_4ddb16_idx')],
            },
        ),
    ]
