# Generated by Django 6.0.5 on 2026-05-11 17:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Rules and instructions shown before starting')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='contest_banners/')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes for each candidate', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private (Invite Only)'), ('password', 'Password Protected')], default='public', max_length=20)),
                ('access_password', models.CharField(blank=True, max_length=100)),
                ('access_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('passing_percentage', models.PositiveIntegerField(default=40, validators=[django.core.validators.MaxValueValidator(100)])),
                ('negative_marking', models.BooleanField(default=False)),
                ('enable_proctoring', models.BooleanField(default=True)),
                ('enable_webcam', models.BooleanField(default=False)),
                ('enable_screen_recording', models.BooleanField(default=False)),
                ('max_violations', models.PositiveIntegerField(default=3)),
                ('auto_submit_on_violation', models.BooleanField(default=True)),
                ('fullscreen_required', models.BooleanField(default=True)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_options', models.BooleanField(default=False)),
                ('show_results_immediately', models.BooleanField(default=False)),
                ('allow_review', models.BooleanField(default=True)),
                ('leaderboard_visible', models.BooleanField(default=True)),
                ('leaderboard_frozen', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contests_contest',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='contests.contest')),
            ],
            options={
                'db_table': 'contests_announcement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='contests.contest')),
            ],
            options={
                'db_table': 'contests_invitation',
            },
        ),
        migrations.CreateModel(
            name='ContestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('auto_submitted', 'Auto-Submitted'), ('disqualified', 'Disqualified')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('time_remaining_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_possible_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('proctoring_data', models.JSONField(blank=True, default=dict)),
                ('system_check_passed', models.BooleanField(default=False)),
                ('camera_granted', models.BooleanField(default=False)),
                ('microphone_granted', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contests_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['status', 'start_time'], name='contests_co_status_72dc20_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['created_by', 'status'], name='contests_co_created_bf2c30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contestinvitation',
            unique_together={('contest', 'email')},
        ),
        migrations.AddIndex(
            model_name='contestsession',
            index=models.Index(fields=['contest', 'status'], name='contests_se_contest_e8b7db_idx'),
        ),
        migrations.AddIndex(
            model_name='contestsession',
            index=models.Index(fields=['user', 'status'], name='contests_se_user_id_764951_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contestsession',
            unique_together={('contest', 'user')},
        ),
    ]
